describe('Create Database, Add an entry, Save', () => {
    it('Prepares Session and Local Db ', () => {
        cy.clearDb();
    });
    it('Create a DB', () => {
        cy.visit('/');
        cy.contains('h1', 'Open a Pwd Database');
        cy.get('a#settings-link').click();
        cy.contains('h1', 'Settings');
        cy.get('a#create-db-link').click();
        cy.contains('h1', 'Create New Database');
        cy.get('input#pwdCalled').type('Cypress Test DB');
        cy.get('input#secretKey').type('abcd1234');
        cy.get('button#create-submit').click();
        cy.contains('p.italic', 'No entries to show');
        cy.get('a#add-link').click();
        cy.contains('h1', 'Add Entry');
        cy.get('input#category-label').type('Banking');
        cy.get('input#title').type('ABC Credit Union');
        cy.get('input#username').type('cypress');
        cy.get('input#password').type('123abc456');
        cy.get('input#url').type('https://login.abccu.org');
        cy.get('button#edit-entry-submit').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.contains('p', 'Banking');
        cy.contains('p', 'ABC Credit Union');
        cy.get('a#details-link-entry-0').click();
        cy.contains('p', 'cypress');
        cy.contains('p', '123abc456');
        cy.contains('p', 'https://login.abccu.org');
        cy.get('a#edit-entry-0').click();
        cy.contains('h1', 'Edit Entry');
        cy.get('textarea#notes').type('ph: 800-555-1212');
        cy.get('button#edit-entry-submit').click();
        cy.contains('p', 'Banking');
        cy.contains('p', 'ABC Credit Union');
        cy.get('a#details-link-entry-0').click();
        cy.contains('pre', 'ph: 800-555-1212');
        cy.contains('p', 'cypress');
        cy.contains('p', '123abc456');
        cy.get('a#quick-save-link').click();
        cy.contains('p', 'Banking');
        cy.contains('p', 'ABC Credit Union');
        cy.get('a#lock-db-link').click();
        cy.contains('h1', 'Open a Pwd Database');
        cy.get('input#database-label').type('cypress');
        cy.get('li#db-item-0').click();
        cy.get('input#secretKey').type('abcd1234');
        cy.get('button#open-db-submit').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.contains('p', 'Banking');
        cy.contains('p', 'ABC Credit Union');
        cy.get('a#details-link-entry-0').click();
        cy.contains('p', 'cypress');
        cy.contains('p', '123abc456');
    });
    it('Test Nav for Open and Close DB', () => {
        cy.visit('/');
        cy.get('#topNavMenu').contains('a', 'Open Db');
        cy.contains('h1', 'Open a Pwd Database');
        cy.get('input#database-label').type('cypress');
        cy.get('li#db-item-0').click();
        cy.get('input#secretKey').type('abcd1234');
        cy.get('button#open-db-submit').click();
        cy.get('#topNavMenu').contains('a', 'Close Db');
        cy.get('#topNavMenu').contains('a', 'Save Db');
        cy.get('#topNavMenu').contains('a', 'Trash');
    });
    it('Add and Trash handling', () => {
        cy.visit('/');
        cy.contains('h1', 'Open a Pwd Database');
        cy.get('input#database-label').type('cypress');
        cy.get('li#db-item-0').click();
        cy.get('input#secretKey').type('abcd1234');
        cy.get('button#open-db-submit').click();
        cy.contains('p', 'Banking');
        cy.contains('p', 'ABC Credit Union');
        cy.get('a#add-link').click();
        cy.contains('h1', 'Add Entry');
        cy.get('input#category-label').type('Internet');
        cy.get('input#title').type('Nham24');
        cy.get('input#username').type('cypress');
        cy.get('input#password').type('goodeats');
        cy.get('input#url').type('https://nham24.com/login');
        cy.get('button#edit-entry-submit').click();
        cy.get('app-entry-card').its('length').should('eq', 2);
        cy.contains('p', 'Internet');
        cy.contains('p', 'Nham24');
        cy.get('a#details-link-entry-1').click();
        cy.contains('p', 'Password');
        cy.contains('p', 'goodeats');
        cy.get('a#trash-entry-1').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#trash-link').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#details-link-entry-1').click();
        cy.get('a#recycle-entry-1').click();
        cy.contains('p.italic', 'No entries to show');
        cy.get('a#return-link').click();
        cy.get('app-entry-card').its('length').should('eq', 2);
        cy.get('a#details-link-entry-1').click();
        cy.get('a#trash-entry-1').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#trash-link').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('button#empty-trash-submit').click();
        cy.contains('p.italic', 'No entries to show');
        cy.get('a#return-link').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#lock-db-link').click();
        cy.contains('h1', 'Open a Pwd Database');
        cy.get('input#database-label').type('cypress');
        cy.get('li#db-item-0').click();
        cy.get('input#secretKey').type('abcd1234');
        cy.get('button#open-db-submit').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#trash-link').click();
        cy.contains('p.italic', 'No entries to show');
        cy.get('a#return-link').click();
        cy.get('app-entry-card').its('length').should('eq', 1);
        cy.get('a#lock-db-link').click();
    });
});
